package pers.chaos.jsondartserializable.core.json.constants;

import java.util.Arrays;
import java.util.List;

public interface GeneratedTemplate {
    interface Header {
        List<String> generatedFileHeaders = Arrays.asList(
                "/// Generated by json-dart-serializable plugin.\n",
                "/// When some incorrect data generated, please fix it.\n",
                "/// Finally, run flutter build_runner auto generate *.g.dart file.\n"
        );
        String jsonSerializablePackAnno = "@JsonSerializable()\n";
        String jsonSerializablePack = "import 'package:json_annotation/json_annotation.dart';\n";
        String otherFileImport = "import '%s';\n";
        String gFileImport = "part '%s.g.dart';\n\n";
        String description = "/// %s\n";
    }

    interface ClassBody {
        String className = "class %s {\n";
        String fieldDescription = "    /// %s\n";
        String fieldJsonKey = "    @JsonKey(name: '%s')\n";
        String field = "    %s %s;\n\n";
        String constructor = "    /// Constructor...\n    %s(%s);\n\n";
        String requiredConstructorPart = "required this.%s, ";
        String requiredConstructorWithDefaultValPart = "required this.%s = %s, ";
        String constructorOnlyDefaultValPart = "this.%s = %s, ";
        String constructorNullablePart = "this.%s, ";
        String fromJson = "    /// Deserializer...\n    factory %s.fromJson(Map<String, dynamic> json) => _$%sFromJson(json);\n\n";
        String toJson = "    /// Serializer...\n    Map<String, dynamic> toJson() => _$%sToJson(this);\n";
        String classEOF = "}";
    }
}
